//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CDetallista.WSTimbrado {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ComprobantesTimbradoSoap", Namespace="http://facturainteligenteintegraciones.com/WSTimbrado")]
    public partial class ComprobantesTimbrado : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TimbrarTxTOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarQROperationCompleted;
        
        private System.Threading.SendOrPostCallback SellarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimbrarXMLconComplementosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCreditosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerAcuseCancelacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerAcuseEnvioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarComplementoTimbreOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarEstadoComprobanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmarRecepcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarCFDIOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistroTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback FacturarTicketOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ComprobantesTimbrado() {
            this.Url = global::CDetallista.Properties.Settings.Default.CDetallista_WSTimbrado_ComprobantesTimbrado;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TimbrarTxTCompletedEventHandler TimbrarTxTCompleted;
        
        /// <remarks/>
        public event GenerarQRCompletedEventHandler GenerarQRCompleted;
        
        /// <remarks/>
        public event SellarCompletedEventHandler SellarCompleted;
        
        /// <remarks/>
        public event ObtenerPDFCompletedEventHandler ObtenerPDFCompleted;
        
        /// <remarks/>
        public event TimbrarXMLconComplementosCompletedEventHandler TimbrarXMLconComplementosCompleted;
        
        /// <remarks/>
        public event ConsultarCreditosCompletedEventHandler ConsultarCreditosCompleted;
        
        /// <remarks/>
        public event ObtenerAcuseCancelacionCompletedEventHandler ObtenerAcuseCancelacionCompleted;
        
        /// <remarks/>
        public event ObtenerAcuseEnvioCompletedEventHandler ObtenerAcuseEnvioCompleted;
        
        /// <remarks/>
        public event ConsultarComplementoTimbreCompletedEventHandler ConsultarComplementoTimbreCompleted;
        
        /// <remarks/>
        public event ConsultarEstadoComprobanteCompletedEventHandler ConsultarEstadoComprobanteCompleted;
        
        /// <remarks/>
        public event ConfirmarRecepcionCompletedEventHandler ConfirmarRecepcionCompleted;
        
        /// <remarks/>
        public event CancelarCFDICompletedEventHandler CancelarCFDICompleted;
        
        /// <remarks/>
        public event RegistroTicketCompletedEventHandler RegistroTicketCompleted;
        
        /// <remarks/>
        public event FacturarTicketCompletedEventHandler FacturarTicketCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/TimbrarTxT", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta TimbrarTxT(PeticionObtenerXML _PeticionCliente) {
            object[] results = this.Invoke("TimbrarTxT", new object[] {
                        _PeticionCliente});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarTxTAsync(PeticionObtenerXML _PeticionCliente) {
            this.TimbrarTxTAsync(_PeticionCliente, null);
        }
        
        /// <remarks/>
        public void TimbrarTxTAsync(PeticionObtenerXML _PeticionCliente, object userState) {
            if ((this.TimbrarTxTOperationCompleted == null)) {
                this.TimbrarTxTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarTxTOperationCompleted);
            }
            this.InvokeAsync("TimbrarTxT", new object[] {
                        _PeticionCliente}, this.TimbrarTxTOperationCompleted, userState);
        }
        
        private void OnTimbrarTxTOperationCompleted(object arg) {
            if ((this.TimbrarTxTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarTxTCompleted(this, new TimbrarTxTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/GenerarQR", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerarQR(string _user, string _password, string _uuid, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] ref byte[] _qr, ref string _error) {
            object[] results = this.Invoke("GenerarQR", new object[] {
                        _user,
                        _password,
                        _uuid,
                        _qr,
                        _error});
            _qr = ((byte[])(results[0]));
            _error = ((string)(results[1]));
        }
        
        /// <remarks/>
        public void GenerarQRAsync(string _user, string _password, string _uuid, byte[] _qr, string _error) {
            this.GenerarQRAsync(_user, _password, _uuid, _qr, _error, null);
        }
        
        /// <remarks/>
        public void GenerarQRAsync(string _user, string _password, string _uuid, byte[] _qr, string _error, object userState) {
            if ((this.GenerarQROperationCompleted == null)) {
                this.GenerarQROperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarQROperationCompleted);
            }
            this.InvokeAsync("GenerarQR", new object[] {
                        _user,
                        _password,
                        _uuid,
                        _qr,
                        _error}, this.GenerarQROperationCompleted, userState);
        }
        
        private void OnGenerarQROperationCompleted(object arg) {
            if ((this.GenerarQRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarQRCompleted(this, new GenerarQRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/Sellar", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta Sellar(string varuser, string varpas, string xmlContenido, string rfcEmisor, string dAdicionales, bool productivo, t_CFDI tipoCFDI, string cadenaComplemento) {
            object[] results = this.Invoke("Sellar", new object[] {
                        varuser,
                        varpas,
                        xmlContenido,
                        rfcEmisor,
                        dAdicionales,
                        productivo,
                        tipoCFDI,
                        cadenaComplemento});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void SellarAsync(string varuser, string varpas, string xmlContenido, string rfcEmisor, string dAdicionales, bool productivo, t_CFDI tipoCFDI, string cadenaComplemento) {
            this.SellarAsync(varuser, varpas, xmlContenido, rfcEmisor, dAdicionales, productivo, tipoCFDI, cadenaComplemento, null);
        }
        
        /// <remarks/>
        public void SellarAsync(string varuser, string varpas, string xmlContenido, string rfcEmisor, string dAdicionales, bool productivo, t_CFDI tipoCFDI, string cadenaComplemento, object userState) {
            if ((this.SellarOperationCompleted == null)) {
                this.SellarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSellarOperationCompleted);
            }
            this.InvokeAsync("Sellar", new object[] {
                        varuser,
                        varpas,
                        xmlContenido,
                        rfcEmisor,
                        dAdicionales,
                        productivo,
                        tipoCFDI,
                        cadenaComplemento}, this.SellarOperationCompleted, userState);
        }
        
        private void OnSellarOperationCompleted(object arg) {
            if ((this.SellarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SellarCompleted(this, new SellarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/ObtenerPDF", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ObtenerPDF(string user, string password, string xmlTimbrado, string adicionales, t_CFDI tipoCFDI, ref string error) {
            object[] results = this.Invoke("ObtenerPDF", new object[] {
                        user,
                        password,
                        xmlTimbrado,
                        adicionales,
                        tipoCFDI,
                        error});
            error = ((string)(results[1]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPDFAsync(string user, string password, string xmlTimbrado, string adicionales, t_CFDI tipoCFDI, string error) {
            this.ObtenerPDFAsync(user, password, xmlTimbrado, adicionales, tipoCFDI, error, null);
        }
        
        /// <remarks/>
        public void ObtenerPDFAsync(string user, string password, string xmlTimbrado, string adicionales, t_CFDI tipoCFDI, string error, object userState) {
            if ((this.ObtenerPDFOperationCompleted == null)) {
                this.ObtenerPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPDFOperationCompleted);
            }
            this.InvokeAsync("ObtenerPDF", new object[] {
                        user,
                        password,
                        xmlTimbrado,
                        adicionales,
                        tipoCFDI,
                        error}, this.ObtenerPDFOperationCompleted, userState);
        }
        
        private void OnObtenerPDFOperationCompleted(object arg) {
            if ((this.ObtenerPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPDFCompleted(this, new ObtenerPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/TimbrarXMLconComplementos", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta TimbrarXMLconComplementos(string user, string password, string xmlconAdd, string rfcEmisor, t_CFDI tipoCFDI, bool sellar, bool productivo) {
            object[] results = this.Invoke("TimbrarXMLconComplementos", new object[] {
                        user,
                        password,
                        xmlconAdd,
                        rfcEmisor,
                        tipoCFDI,
                        sellar,
                        productivo});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarXMLconComplementosAsync(string user, string password, string xmlconAdd, string rfcEmisor, t_CFDI tipoCFDI, bool sellar, bool productivo) {
            this.TimbrarXMLconComplementosAsync(user, password, xmlconAdd, rfcEmisor, tipoCFDI, sellar, productivo, null);
        }
        
        /// <remarks/>
        public void TimbrarXMLconComplementosAsync(string user, string password, string xmlconAdd, string rfcEmisor, t_CFDI tipoCFDI, bool sellar, bool productivo, object userState) {
            if ((this.TimbrarXMLconComplementosOperationCompleted == null)) {
                this.TimbrarXMLconComplementosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarXMLconComplementosOperationCompleted);
            }
            this.InvokeAsync("TimbrarXMLconComplementos", new object[] {
                        user,
                        password,
                        xmlconAdd,
                        rfcEmisor,
                        tipoCFDI,
                        sellar,
                        productivo}, this.TimbrarXMLconComplementosOperationCompleted, userState);
        }
        
        private void OnTimbrarXMLconComplementosOperationCompleted(object arg) {
            if ((this.TimbrarXMLconComplementosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarXMLconComplementosCompleted(this, new TimbrarXMLconComplementosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/ConsultarCreditos", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarCreditos(string usuario, string contrasena) {
            object[] results = this.Invoke("ConsultarCreditos", new object[] {
                        usuario,
                        contrasena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCreditosAsync(string usuario, string contrasena) {
            this.ConsultarCreditosAsync(usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void ConsultarCreditosAsync(string usuario, string contrasena, object userState) {
            if ((this.ConsultarCreditosOperationCompleted == null)) {
                this.ConsultarCreditosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCreditosOperationCompleted);
            }
            this.InvokeAsync("ConsultarCreditos", new object[] {
                        usuario,
                        contrasena}, this.ConsultarCreditosOperationCompleted, userState);
        }
        
        private void OnConsultarCreditosOperationCompleted(object arg) {
            if ((this.ConsultarCreditosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCreditosCompleted(this, new ConsultarCreditosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/ObtenerAcuseCancelacion", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerAcuseCancelacion(string usuario, string contrasena, string UUID, string EmisorRFC) {
            object[] results = this.Invoke("ObtenerAcuseCancelacion", new object[] {
                        usuario,
                        contrasena,
                        UUID,
                        EmisorRFC});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerAcuseCancelacionAsync(string usuario, string contrasena, string UUID, string EmisorRFC) {
            this.ObtenerAcuseCancelacionAsync(usuario, contrasena, UUID, EmisorRFC, null);
        }
        
        /// <remarks/>
        public void ObtenerAcuseCancelacionAsync(string usuario, string contrasena, string UUID, string EmisorRFC, object userState) {
            if ((this.ObtenerAcuseCancelacionOperationCompleted == null)) {
                this.ObtenerAcuseCancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerAcuseCancelacionOperationCompleted);
            }
            this.InvokeAsync("ObtenerAcuseCancelacion", new object[] {
                        usuario,
                        contrasena,
                        UUID,
                        EmisorRFC}, this.ObtenerAcuseCancelacionOperationCompleted, userState);
        }
        
        private void OnObtenerAcuseCancelacionOperationCompleted(object arg) {
            if ((this.ObtenerAcuseCancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerAcuseCancelacionCompleted(this, new ObtenerAcuseCancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/ObtenerAcuseEnvio", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerAcuseEnvio(string usuario, string contrasena, string UUID, string EmisorRFC) {
            object[] results = this.Invoke("ObtenerAcuseEnvio", new object[] {
                        usuario,
                        contrasena,
                        UUID,
                        EmisorRFC});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerAcuseEnvioAsync(string usuario, string contrasena, string UUID, string EmisorRFC) {
            this.ObtenerAcuseEnvioAsync(usuario, contrasena, UUID, EmisorRFC, null);
        }
        
        /// <remarks/>
        public void ObtenerAcuseEnvioAsync(string usuario, string contrasena, string UUID, string EmisorRFC, object userState) {
            if ((this.ObtenerAcuseEnvioOperationCompleted == null)) {
                this.ObtenerAcuseEnvioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerAcuseEnvioOperationCompleted);
            }
            this.InvokeAsync("ObtenerAcuseEnvio", new object[] {
                        usuario,
                        contrasena,
                        UUID,
                        EmisorRFC}, this.ObtenerAcuseEnvioOperationCompleted, userState);
        }
        
        private void OnObtenerAcuseEnvioOperationCompleted(object arg) {
            if ((this.ObtenerAcuseEnvioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerAcuseEnvioCompleted(this, new ObtenerAcuseEnvioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/ConsultarComplementoTimbre", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarComplementoTimbre(string usuario, string contrasena, string UUID) {
            object[] results = this.Invoke("ConsultarComplementoTimbre", new object[] {
                        usuario,
                        contrasena,
                        UUID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarComplementoTimbreAsync(string usuario, string contrasena, string UUID) {
            this.ConsultarComplementoTimbreAsync(usuario, contrasena, UUID, null);
        }
        
        /// <remarks/>
        public void ConsultarComplementoTimbreAsync(string usuario, string contrasena, string UUID, object userState) {
            if ((this.ConsultarComplementoTimbreOperationCompleted == null)) {
                this.ConsultarComplementoTimbreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarComplementoTimbreOperationCompleted);
            }
            this.InvokeAsync("ConsultarComplementoTimbre", new object[] {
                        usuario,
                        contrasena,
                        UUID}, this.ConsultarComplementoTimbreOperationCompleted, userState);
        }
        
        private void OnConsultarComplementoTimbreOperationCompleted(object arg) {
            if ((this.ConsultarComplementoTimbreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarComplementoTimbreCompleted(this, new ConsultarComplementoTimbreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/ConsultarEstadoComprobante", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarEstadoComprobante(string usuario, string contrasena, string UUID) {
            object[] results = this.Invoke("ConsultarEstadoComprobante", new object[] {
                        usuario,
                        contrasena,
                        UUID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarEstadoComprobanteAsync(string usuario, string contrasena, string UUID) {
            this.ConsultarEstadoComprobanteAsync(usuario, contrasena, UUID, null);
        }
        
        /// <remarks/>
        public void ConsultarEstadoComprobanteAsync(string usuario, string contrasena, string UUID, object userState) {
            if ((this.ConsultarEstadoComprobanteOperationCompleted == null)) {
                this.ConsultarEstadoComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarEstadoComprobanteOperationCompleted);
            }
            this.InvokeAsync("ConsultarEstadoComprobante", new object[] {
                        usuario,
                        contrasena,
                        UUID}, this.ConsultarEstadoComprobanteOperationCompleted, userState);
        }
        
        private void OnConsultarEstadoComprobanteOperationCompleted(object arg) {
            if ((this.ConsultarEstadoComprobanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarEstadoComprobanteCompleted(this, new ConsultarEstadoComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/ConfirmarRecepcion", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfirmarRecepcion(string usuario, string contrasena, string UUID) {
            object[] results = this.Invoke("ConfirmarRecepcion", new object[] {
                        usuario,
                        contrasena,
                        UUID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmarRecepcionAsync(string usuario, string contrasena, string UUID) {
            this.ConfirmarRecepcionAsync(usuario, contrasena, UUID, null);
        }
        
        /// <remarks/>
        public void ConfirmarRecepcionAsync(string usuario, string contrasena, string UUID, object userState) {
            if ((this.ConfirmarRecepcionOperationCompleted == null)) {
                this.ConfirmarRecepcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmarRecepcionOperationCompleted);
            }
            this.InvokeAsync("ConfirmarRecepcion", new object[] {
                        usuario,
                        contrasena,
                        UUID}, this.ConfirmarRecepcionOperationCompleted, userState);
        }
        
        private void OnConfirmarRecepcionOperationCompleted(object arg) {
            if ((this.ConfirmarRecepcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmarRecepcionCompleted(this, new ConfirmarRecepcionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/CancelarCFDI", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] CancelarCFDI(string usuario, string contrasena, string RfcEmisor, string UUID, ref string MyError) {
            object[] results = this.Invoke("CancelarCFDI", new object[] {
                        usuario,
                        contrasena,
                        RfcEmisor,
                        UUID,
                        MyError});
            MyError = ((string)(results[1]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void CancelarCFDIAsync(string usuario, string contrasena, string RfcEmisor, string UUID, string MyError) {
            this.CancelarCFDIAsync(usuario, contrasena, RfcEmisor, UUID, MyError, null);
        }
        
        /// <remarks/>
        public void CancelarCFDIAsync(string usuario, string contrasena, string RfcEmisor, string UUID, string MyError, object userState) {
            if ((this.CancelarCFDIOperationCompleted == null)) {
                this.CancelarCFDIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarCFDIOperationCompleted);
            }
            this.InvokeAsync("CancelarCFDI", new object[] {
                        usuario,
                        contrasena,
                        RfcEmisor,
                        UUID,
                        MyError}, this.CancelarCFDIOperationCompleted, userState);
        }
        
        private void OnCancelarCFDIOperationCompleted(object arg) {
            if ((this.CancelarCFDICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarCFDICompleted(this, new CancelarCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/RegistroTicket", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RRegistroTicket RegistroTicket(RegistroTicket pet) {
            object[] results = this.Invoke("RegistroTicket", new object[] {
                        pet});
            return ((RRegistroTicket)(results[0]));
        }
        
        /// <remarks/>
        public void RegistroTicketAsync(RegistroTicket pet) {
            this.RegistroTicketAsync(pet, null);
        }
        
        /// <remarks/>
        public void RegistroTicketAsync(RegistroTicket pet, object userState) {
            if ((this.RegistroTicketOperationCompleted == null)) {
                this.RegistroTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistroTicketOperationCompleted);
            }
            this.InvokeAsync("RegistroTicket", new object[] {
                        pet}, this.RegistroTicketOperationCompleted, userState);
        }
        
        private void OnRegistroTicketOperationCompleted(object arg) {
            if ((this.RegistroTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistroTicketCompleted(this, new RegistroTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://facturainteligenteintegraciones.com/WSTimbrado/FacturarTicket", RequestNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", ResponseNamespace="http://facturainteligenteintegraciones.com/WSTimbrado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta FacturarTicket(CambioTicket pet) {
            object[] results = this.Invoke("FacturarTicket", new object[] {
                        pet});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void FacturarTicketAsync(CambioTicket pet) {
            this.FacturarTicketAsync(pet, null);
        }
        
        /// <remarks/>
        public void FacturarTicketAsync(CambioTicket pet, object userState) {
            if ((this.FacturarTicketOperationCompleted == null)) {
                this.FacturarTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFacturarTicketOperationCompleted);
            }
            this.InvokeAsync("FacturarTicket", new object[] {
                        pet}, this.FacturarTicketOperationCompleted, userState);
        }
        
        private void OnFacturarTicketOperationCompleted(object arg) {
            if ((this.FacturarTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FacturarTicketCompleted(this, new FacturarTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturainteligenteintegraciones.com/WSTimbrado")]
    public partial class PeticionObtenerXML {
        
        private string usuarioField;
        
        private string contrasenaField;
        
        private string cadenaTXTField;
        
        private string rfcEmisorField;
        
        private t_CFDI tipoCFDIField;
        
        private bool productivoField;
        
        private string cadenaComplementoField;
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        /// <comentarios/>
        public string cadenaTXT {
            get {
                return this.cadenaTXTField;
            }
            set {
                this.cadenaTXTField = value;
            }
        }
        
        /// <comentarios/>
        public string rfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
            }
        }
        
        /// <comentarios/>
        public t_CFDI tipoCFDI {
            get {
                return this.tipoCFDIField;
            }
            set {
                this.tipoCFDIField = value;
            }
        }
        
        /// <comentarios/>
        public bool productivo {
            get {
                return this.productivoField;
            }
            set {
                this.productivoField = value;
            }
        }
        
        /// <comentarios/>
        public string cadenaComplemento {
            get {
                return this.cadenaComplementoField;
            }
            set {
                this.cadenaComplementoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturainteligenteintegraciones.com/WSTimbrado")]
    public enum t_CFDI {
        
        /// <comentarios/>
        Factura,
        
        /// <comentarios/>
        NotadeCredito,
        
        /// <comentarios/>
        RecibodeHonorarios,
        
        /// <comentarios/>
        RecibodeArrendamiento,
        
        /// <comentarios/>
        RecibodePago,
        
        /// <comentarios/>
        RecibodeDonativo,
        
        /// <comentarios/>
        NotadeCargo,
        
        /// <comentarios/>
        NotadeDevolucion,
        
        /// <comentarios/>
        CartaPorte,
        
        /// <comentarios/>
        CartaPorteIngreso,
        
        /// <comentarios/>
        RecibodeIngreso,
        
        /// <comentarios/>
        RecibodeNomina,
        
        /// <comentarios/>
        FacturaAcreditamientoIEPS,
        
        /// <comentarios/>
        FacturaConstructoras,
        
        /// <comentarios/>
        FacturaAerolineas,
        
        /// <comentarios/>
        FacturaInsEducativas,
        
        /// <comentarios/>
        FacturaVehiculoUsado,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturainteligenteintegraciones.com/WSTimbrado")]
    public partial class CambioTicket {
        
        private string usuarioField;
        
        private string passwordField;
        
        private string qticketField;
        
        private string rfcEmisorField;
        
        /// <comentarios/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <comentarios/>
        public string qticket {
            get {
                return this.qticketField;
            }
            set {
                this.qticketField = value;
            }
        }
        
        /// <comentarios/>
        public string rfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturainteligenteintegraciones.com/WSTimbrado")]
    public partial class RRegistroTicket {
        
        private bool exitoField;
        
        private string errorField;
        
        /// <comentarios/>
        public bool exito {
            get {
                return this.exitoField;
            }
            set {
                this.exitoField = value;
            }
        }
        
        /// <comentarios/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturainteligenteintegraciones.com/WSTimbrado")]
    public partial class RegistroTicket {
        
        private string noticketField;
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        private string cadeTxtField;
        
        /// <comentarios/>
        public string noticket {
            get {
                return this.noticketField;
            }
            set {
                this.noticketField = value;
            }
        }
        
        /// <comentarios/>
        public string rfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
            }
        }
        
        /// <comentarios/>
        public string rfcReceptor {
            get {
                return this.rfcReceptorField;
            }
            set {
                this.rfcReceptorField = value;
            }
        }
        
        /// <comentarios/>
        public string cadeTxt {
            get {
                return this.cadeTxtField;
            }
            set {
                this.cadeTxtField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturainteligenteintegraciones.com/WSTimbrado")]
    public partial class Respuesta {
        
        private bool exitoField;
        
        private string errorGeneralField;
        
        private string errorEspecificoField;
        
        private byte[] xmlTimbradoField;
        
        private byte[] pdfField;
        
        private string uuidField;
        
        /// <comentarios/>
        public bool exito {
            get {
                return this.exitoField;
            }
            set {
                this.exitoField = value;
            }
        }
        
        /// <comentarios/>
        public string errorGeneral {
            get {
                return this.errorGeneralField;
            }
            set {
                this.errorGeneralField = value;
            }
        }
        
        /// <comentarios/>
        public string errorEspecifico {
            get {
                return this.errorEspecificoField;
            }
            set {
                this.errorEspecificoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] xmlTimbrado {
            get {
                return this.xmlTimbradoField;
            }
            set {
                this.xmlTimbradoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
            }
        }
        
        /// <comentarios/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void TimbrarTxTCompletedEventHandler(object sender, TimbrarTxTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbrarTxTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbrarTxTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GenerarQRCompletedEventHandler(object sender, GenerarQRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarQRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarQRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] _qr {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string _error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SellarCompletedEventHandler(object sender, SellarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SellarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SellarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ObtenerPDFCompletedEventHandler(object sender, ObtenerPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void TimbrarXMLconComplementosCompletedEventHandler(object sender, TimbrarXMLconComplementosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbrarXMLconComplementosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbrarXMLconComplementosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConsultarCreditosCompletedEventHandler(object sender, ConsultarCreditosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCreditosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCreditosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ObtenerAcuseCancelacionCompletedEventHandler(object sender, ObtenerAcuseCancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerAcuseCancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerAcuseCancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ObtenerAcuseEnvioCompletedEventHandler(object sender, ObtenerAcuseEnvioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerAcuseEnvioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerAcuseEnvioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConsultarComplementoTimbreCompletedEventHandler(object sender, ConsultarComplementoTimbreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarComplementoTimbreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarComplementoTimbreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConsultarEstadoComprobanteCompletedEventHandler(object sender, ConsultarEstadoComprobanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarEstadoComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarEstadoComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConfirmarRecepcionCompletedEventHandler(object sender, ConfirmarRecepcionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmarRecepcionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmarRecepcionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CancelarCFDICompletedEventHandler(object sender, CancelarCFDICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelarCFDICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelarCFDICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string MyError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RegistroTicketCompletedEventHandler(object sender, RegistroTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistroTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistroTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RRegistroTicket Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RRegistroTicket)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void FacturarTicketCompletedEventHandler(object sender, FacturarTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FacturarTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FacturarTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591